version: '3'
services:
  web:
    image: mood-tracker:latest
    ports:
      - "9090:8080"
    depends_on:
      - redis
  redis:
    image: redis
    ports:
      - "6379:6379"
volumes:
  logvolume01: {}